apiVersion: v1
kind: Pod
metadata:
  name: portfoliosecuritybatch
spec:
  containers:
    - name: portfoliosecuritybatch
      image: portfoliosecuritybatch:latest
      imagePullPolicy: Never
      volumeMounts:
      - name: secrets
        mountPath: /app/secrets
        readOnly: true
      - name: tz-config
        mountPath: /etc/localtime
      - name: nlog-config
        mountPath: /app/NLog.config
        subPath: NLog.config
  volumes:
    - name: secrets
      secret:
       secretName: securitydataprovider-secret
    - name: tz-config
      hostPath:
        path: /usr/share/zoneinfo/Europe/Rome
    - name: nlog-config
      configMap:
       name: nlog-configmap